title: Your underwheming title
author: the unnamed wanderer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place for tumbleweeds to gather against fences and for the lost and aimless to lounge around the campfire waiting for splines to reticulate. 

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
